let N = 32;
let M = 20;

// binary strings representating state samples generated by the trained RBM
let strings = [
  "00000000000000000000000100000010",
  "10000000110000100000000000000000",
  "11111111101111111101111111111111",
  "11111011011111111111111100000111",
  "10011011001000000011111111111111",
  "11111111111111110111110101101111",
  "11111111111111110010011111111111",
  "11111111111111111111110000011001",
  "11111111101000011111000111111111",
  "11111111111111111110111111111111",
  "10000111011111110001000011110000",
  "00000000000000000000000000010000",
  "00000000010010110000000000000000",
  "00000000000000000000001110000000",
  "00000001100000000000000000000000",
  "00001000100000010000000000000100",
  "00000000000000010000000000000000",
  "00000000000000010000100001101100",
  "00010101000000000000010000000000",
  "11111111111111111110111111111011",
];

// state control
let currentIndex = 0;
let progress = 0;
let flipFrames = 10;
let holdFrames = 20;
let mode = "hold";
let frameInPhase = 0;

function setup() {
  createCanvas(1200, 200);
  frameRate(30);
}

function draw() {
  background(255);

  let s0 = strings[currentIndex];
  let s1 = strings[(currentIndex + 1) % M];

  let y = height / 2;
  let spacing = width / (N + 1);

  // progress control
  if (mode === "hold") {
    progress = 0;
  } else if (mode === "flip") {
    progress = frameInPhase / flipFrames;
    if (progress > 1) progress = 1;
  }

  // draw the arrows
  for (let i = 0; i < N; i++) {
    let x = spacing * (i + 1);

    let b0 = s0[i];
    let b1 = s1[i];

    let baseAngleCurrent = (b0 === "1") ? 0 : PI;
    let angle;

    if (mode === "hold") {
      angle = baseAngleCurrent;
    } else {
      if (b0 === b1) {
        angle = baseAngleCurrent;
      } else {
        angle = baseAngleCurrent + progress * PI;
      }
    }

    drawArrow(x, y, angle);
  }

  // phase update
  frameInPhase++;

  if (mode === "hold") {
    if (frameInPhase >= holdFrames) {
      mode = "flip";
      frameInPhase = 0;
    }
  } else if (mode === "flip") {
    if (frameInPhase >= flipFrames) {
      mode = "hold";
      frameInPhase = 0;
      currentIndex = (currentIndex + 1) % M;
    }
  }

  // bottom left caption
  drawCaption();

  // bottom right caption
  drawStatusText();
}

function drawArrow(x, y, angle) {
  push();
  translate(x, y);
  rotate(angle);

  stroke(0);
  strokeWeight(2);
  line(0, 10, 0, -10);
  line(0, -10, -5, -3);
  line(0, -10, 5, -3);

  pop();
}

// bottom right caption
function drawStatusText() {
  let textStr = `${currentIndex + 1} / ${M}`;
  textSize(20);
  fill(0);
  noStroke();

  let padding = 10;
  let w = textWidth(textStr);

  let x = width - w - padding;
  let y = height - padding;

  text(textStr, x, y);
}

// bottom left caption
function drawCaption() {
  let caption = "1-D TFIM, states sampled from an RBM trained with VMC";
  textSize(20);
  fill(0);
  noStroke();

  let padding = 10;
  let x = padding;
  let y = height - padding;

  text(caption, x, y);
}

